### ISSUE TITLE
Selected Item's Font too Dark

### ISSUE THREAD

**Issue by Manant02** [pop-os/launcher#59]
The text of the selected search result is almost illegible as the font has almost the same color as it's background. The font color should really just stay the same (maybe become a teeny tiny bit darker).

This is of course using the system's Dark theme.
Running on Pop!_OS 21.4.

![image](https://user-images.githubusercontent.com/51676750/141306566-34ed6e0c-2469-4f35-bdd1-c10b420ccb65.png)

**Comment by jacobgkau** [comment]
Thank you for the report. This may be a duplicate of https://github.com/pop-os/shell/issues/132 and most likely belongs in the pop-shell repo, since this pop-launcher repo only contains backend code and the GUI is handled by pop-shell.

Have you used a different shell theme, application theme, or any other theme in the past? Can you please provide the output of `apt policy pop-shell pop-launcher` to confirm which versions you're currently running? Does the issue happen in a new user account?

**Comment by mmstick** [comment]
I've heard reports that this is fixed in the latest release of GNOME.

**Comment by Manant02** [comment]
> Have you used a different shell theme, application theme, or any other theme in the past? Can you please provide the output of `apt policy pop-shell pop-launcher` to confirm which versions you're currently running? Does the issue happen in a new user account?

Not that I am aware of. Here's the output:
```
manman@pop-os:~$ apt policy pop-shell pop-launcher
pop-shell:
  Installed: 1.1.0~1635267414~21.04~1fddaa8
  Candidate: 1.1.0~1635267414~21.04~1fddaa8
  Version table:
 *** 1.1.0~1635267414~21.04~1fddaa8 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
pop-launcher:
  Installed: 1.0.3~1635692914~21.04~170c6bb
  Candidate: 1.0.3~1635692914~21.04~170c6bb
  Version table:
 *** 1.0.3~1635692914~21.04~170c6bb 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
```


>I've heard reports that this is fixed in the latest release of GNOME.

Is this already in the latest update of Pop!_OS? I recently performed some Operating System Updates through the PopShop and the issue still persists.
